name: Release

# Run on every commit tag which begins with "v" (e.g., "v0.1.4")
on:
  push:
    tags:
      - 'v*'
  pull_request:
    branches:
      - main

jobs:
  build:
    name: 'Release'
    runs-on: 'windows-latest'
    steps:
      - uses: actions/checkout@v4

      - name: Setup NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 20
      
      - name: install dependencies
        run: npm i

      - name: Build
        run: npm run dist

      - name: Release
        uses: 'marvinpinto/action-automatic-releases@latest'
        with:
          repo_token: '${{ secrets.GITHUB_TOKEN }}'
          prerelease: false
          files: |
            dist/League-Observer-Tool-Setup-${{ github.ref, 'refs/tags/v' }}.exe
            dist/League-Observer-Tool-Setup-${{ github.ref, 'refs/tags/v' }}.exe.blockmap
            dist/latest.yml